# FILE: clip-sae-interpret_clean/configs/train_food101_512d.yaml

storage:
  yandex_root: "/content/yadisk/SAE_PROJECT"
  google_root: "/content/drive/MyDrive/SAE_PROJECT"
  logs_dir: "/content/drive/MyDrive/SAE_PROJECT/logs"

data:
  dataset: "food101"
  activations_file: "activations_food101_vit_b32.pt"
  extract_if_missing: false

model:
  input_dim: 512
  latent_dim: 4096

training:
  epochs: 50
  lr: 0.0005      # Явно указано как float
  l1_coef: 0.001  # Явно указано как float
  batch_size: 256
  num_workers: 2

saving:
  checkpoints_dir: "models/sae_food101_512d"
  save_every: 10
  model_name: "sae_food101_512d"